# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_SOC_IMX6Q) += \
	imx6dl-smarc.dtb \
	imx6dl-smarc-wvga.dtb \
	imx6dl-smarc-wxga.dtb \
	imx6dl-smarc-xga.dtb \
	imx6dl-smarc-1080p.dtb \
	imx6q-smarc.dtb \
	imx6q-smarc-wvga.dtb \
	imx6q-smarc-wxga.dtb \
	imx6q-smarc-xga.dtb \
	imx6q-smarc-1080p.dtb \
	imx6qp-smarc.dtb \
	imx6qp-smarc-wvga.dtb \
	imx6qp-smarc-wxga.dtb \
	imx6qp-smarc-xga.dtb \
	imx6qp-smarc-1080p.dtb

dtb-$(CONFIG_SOC_IMX7D) += \
	imx7s-smarc.dtb \
	imx7d-smarc.dtb
