# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_MXC) += imx8mp-smarc.dtb \
			  imx8mp-pitx-rs485.dtb \
			  imx8mp-smarc-hdmi.dtb \
			  imx8mp-smarc-lvds.dtb \
			  imx8mp-pitx-lvds-rs485.dtb \
			  imx8mp-smarc-m7.dtb \
			  imx8mp-pitx.dtb \
			  imx8mp-pitx-lvds.dtb
