dtb-$(CONFIG_ARCH_FSL_IMX8MQ) += fsl-smarcimx8mq.dtb \
                                 fsl-smarcimx8mq-dcss-lvds.dtb \
                                 fsl-smarcimx8mq-dual-display.dtb \
				 fsl-smarcimx8mq-lcdif-lvds.dtb \
				 fsl-smarcimx8mq-dp.dtb \
				 fsl-smarcimx8mq-edp.dtb \
                                 fsl-smarcimx8mq-hdmi.dtb \
				 fsl-smarcimx8mq-m4.dtb \
                                 fsl-smarcimx8mq-m4-dcss-lvds.dtb \
                                 fsl-smarcimx8mq-m4-dual-display.dtb \
                                 fsl-smarcimx8mq-m4-lcdif-lvds.dtb \
                                 fsl-smarcimx8mq-m4-dp.dtb \
                                 fsl-smarcimx8mq-m4-hdmi.dtb 
