# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_MXC) += imx8mp-smarc.dtb \
			imx8mp-smarc-hdmi.dtb \
			imx8mp-smarc-lvds.dtb \
			imx8mp-smarc-m7.dtb \
			imx8mq-smarc.dtb \
			imx8mq-smarc-hdmi.dtb \
			imx8mq-smarc-dp.dtb \
			imx8mq-smarc-dcss-lvds.dtb \
			imx8mq-smarc-lcdif-lvds.dtb \
			imx8mq-smarc-dual-display.dtb \
			imx8mq-smarc-m4.dtb \
			imx8mq-smarc-m4-hdmi.dtb \
			imx8mq-smarc-m4-dp.dtb \
			imx8mq-smarc-m4-dcss-lvds.dtb \
			imx8mq-smarc-m4-lcdif-lvds.dtb \
			imx8mq-smarc-m4-dual-display.dtb \
			imx8mm-smarc.dtb \
			imx8mm-smarc-m4.dtb \
			imx8qm-smarc.dtb \
			imx8qm-smarc-dp.dtb \
			imx8qm-smarc-hdmi.dtb \
			imx8qm-smarc-rpmsg.dtb \
			imx8qm-smarc-lvds.dtb \
			imx8qm-smarc-edp.dtb
